# Generated by Django 5.1.3 on 2024-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_newsarticle_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
