# .github/workflows/deploy.yml
name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Backend and Frontend CI"]
    types:
      - completed
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Heroku remote
        run: git remote add heroku https://git.heroku.com/archi-media-master.git

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: archi-media-master
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: master