# .github/workflows/deploy.yml
name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Backend and Frontend CI"]
    types:
      - completed
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: heroku/heroku-deploy@v1.2.4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: archi-media-master
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: master